services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldbcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: storedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev 
      SERVICE_NAME: mysqldb 
    networks:
      - app-network
  
  nodejsapp:
    build:
      context: ./   
      dockerfile: Dockerfile
    container_name: nodejscontainer
    depends_on:
      - mysqldb
    restart: unless-stopped
    # working_dir: /app
    # volumes:
    #   - ./app:/app  
    ports:
      - 5555:5555
    env_file:
      - .env 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

      